# Generated by Django 5.2.4 on 2026-07-16 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_api_key_id', models.PositiveIntegerField(verbose_name='API 9Router')),
                ('api_name', models.CharField(max_length=255, verbose_name='Tên API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phân quyền API',
                'verbose_name_plural': 'Phân quyền API',
                'ordering': ['user__username', 'api_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'external_api_key_id'), name='unique_user_external_api_key')],
            },
        ),
    ]
