# Generated by Django 5.2.4 on 2026-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapiaccess',
            name='external_api_key_id',
            field=models.CharField(max_length=64, verbose_name='API 9Router'),
        ),
    ]
