# Generated by Django 5.2.4 on 2026-07-17 06:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_customeraccount_managedapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedapikey',
            name='closed_cost',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12),
        ),
    ]
