# Generated by Django 5.2.4 on 2026-07-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_managedapikey_closed_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapiaccess',
            name='external_api_key_id',
            field=models.CharField(max_length=64, verbose_name='API ALT'),
        ),
    ]
