# Generated by Django 5.2.4 on 2026-07-17 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_customeraccount_low_credit_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('purchase_usd', models.PositiveSmallIntegerField()),
                ('amount_vnd', models.PositiveBigIntegerField()),
                ('provider_credit_usd', models.DecimalField(decimal_places=4, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán'), ('underpaid', 'Thanh toán thiếu'), ('manual_review', 'Cần kiểm tra thủ công'), ('expired', 'Đã hết hạn')], db_index=True, default='pending', max_length=20)),
                ('received_amount_vnd', models.PositiveBigIntegerField(default=0)),
                ('sepay_transaction_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('credit_limit_before', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('credit_limit_after', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SePayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=160, unique=True)),
                ('amount_vnd', models.PositiveBigIntegerField(default=0)),
                ('transfer_content', models.CharField(blank=True, max_length=500)),
                ('payload_hash', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='dashboard.tokenpurchase')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
    ]
