# Generated by Django 5.2.4 on 2026-07-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_tokenpurchase_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpurchase',
            name='invoice_code',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='PaymentCodeLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=7, unique=True)),
                ('reserved_until', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_code_lease', to='dashboard.tokenpurchase')),
            ],
        ),
    ]
