# Generated by Django 5.2.4 on 2026-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_tokenpurchase_invoice_code_paymentcodelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='is_verified_telegram',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực Telegram'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='telegram_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Mã OTP Telegram'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='telegram_otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời gian tạo OTP Telegram'),
        ),
    ]
